---
title: "UFRGS - Especialização em Ciência de Dados SERPRO - INF/UFRGS (2022-2023)"
#output: md_document
output: html_document
---

|                 |                        |
|-----------------|------------------------|
| **Disciplina**  |      :CD001-Estatística|
| **Professora**  |          :Lisiane Selau|
| **Aluno**       | :Strauss Cunha Carvalho|
| **Labarotório** |                 :LAB-02|
| **Data**        |             :12/03/2022|


<br>

```{r}
#install.packages("ggplot2")
#install.packages("dplyr")
#install.packages("gridExtra")
library(ggplot2)
library(dplyr, warn.conflicts = FALSE)
library("gridExtra", warn.conflicts = FALSE)
```
<br>

##### **LAB-02** - Tarefas do Laboratório 2
<br>

##### **Utilizando a função calc_streak, calcule o comprimento das sequências do vetor sim_basket.**

##### **1. Descreva a distribuição das sequências de arremessos. Qual é o comprimento de sequência típico para o arremessador independente simulado com um percentual de arremesso de 45%? Quão longa é a sequência mais longa de cestas em 133 arremessos?**
<br>

##### **2. Se você rodasse a simulação do arremessador independente uma segunda vez, como você acha que seria a distribuição de sequências em relação à distribuição da questão acima? Exatamente a mesma?**

##### **Mais ou menos parecida? Completamente diferente? Explique seu raciocínio.**
<br>

##### **3. Como a distribuição dos comprimentos de sequência de Kobe Bryant, analisada na página 2, se comparam à distribuição de comprimentos de sequência do arremessador simulado? Utilizando essa comparação, você tem evidência de que o modelo das mãos quentes se ajusta aos padrões de arremessos de Kobe? Explique.**
